// var human_sea_eft = {
//   male: ["Ake",
//   "Arvid",
//   "Audun",
//   "Balder",
//   "Birger",
//   "Bjarke",
//   "Bjorn",
//   "Calder",
//   "Carr",
//   "Colbjorn",
//   "Colden",
//   "Dag",
//   "Egil",
//   "Einar",
//   "Eirik",
//   "Elof",
//   "Erland",
//   "Fell",
//   "Fenrir",
//   "Fiske",
//   "Frey",
//   "Geir",
//   "Gosta",
//   "Godbrand",
//   "Godmund",
//   "Golbrand",
//   "Gonnar",
//   "Gostaf",
//   "Hagen",
//   "Hakon",
//   "Haldor",
//   "Halstein",
//   "Halvar",
//   "Halvard",
//   "Halvor",
//   "Haskell",
//   "Herleif",
//   "Hjalmar",
//   "Holger",
//   "Igor",
//   "Ingemar",
//   "Ingvar",
//   "Ivar",
//   "Iver",
//   "Jari",
//   "Jerrik",
//   "Keld",
//   "Kjeld",
//   "Knud",
//   "Kustaa",
//   "Lamont",
//   "Latham",
//   "Leif",
//   "Lok",
//   "Olaf",
//   "Olin",
//   "Oluf",
//   "Rangvald",
//   "Sigurd",
//   "Stein",
//   "Stigr",
//   "Sven",
//   "Tarben",
//   "Torbjorn",
//   "Torvald",
//   "Ulf",
//   "Vidar"];

//   female: ["Alkhild",
//   "Ase",
//   "Aslaug",
//   "Aslog",
//   "Asta",
//   "Astrid",
//   "Aubhild",
//   "Bodil",
//   "Borghild",
//   "Brenna",
//   "Dagmar",
//   "Dagny",
//   "Eira",
//   "Embla",
//   "Freja",
//   "Gerd",
//   "Gull",
//   "Gunhild",
//   "Gunvor",
//   "Gyda",
//   "Hege",
//   "Helga",
//   "Hertha",
//   "Ingeborg",
//   "Inger",
//   "Ingrid",
//   "Jorunn",
//   "Kari",
//   "Magnhild",
//   "Olga",
//   "Ragna",
//   "Saga",
//   "Sigfrid",
//   "Sigrid",
//   "Sigrun",
//   "Siv",
//   "Solvig",
//   "Solvi",
//   "Svorga",
//   "Thora",
//   "Torborg",
//   "Torhild",
//   "Tove",
//   "Tyra",
//   "Ylva",
//   "Jerrik",
//   "Keld",
//   "Kjeld",
//   "Knud",
//   "Kustaa",
//   "Lamont",
//   "Latham",
//   "Leif",
//   "Lok",
//   "Olaf",
//   "Olin",
//   "Oluf",
//   "Rangvald",
//   "Sigurd",
//   "Stein",
//   "Stigr",
//   "Sven",
//   "Tarben",
//   "Torbjorn",
//   "Torvald",
//   "Ulf",
//   "Vidar"];
//   };

// var human_old_eftirlandic = {
//   male: ["Afe",
//   "Arvid",
//   "Audun",
//   "Baldir",
//   "Birkir",
//   "Bjarfe",
//   "Bjurn",
//   "Caldir",
//   "Carr",
//   "Culbjurn",
//   "Culden",
//   "Dak",
//   "Ekil",
//   "Einar",
//   "Eirik",
//   "Eluf",
//   "Erland",
//   "Fell",
//   "Fiske",
//   "Frey",
//   "Keir",
//   "Kusta",
//   "Kudbrand",
//   "Kudmund",
//   "Kulbrand",
//   "Kunnar",
//   "Kustav",
//   "Haken",
//   "Hakun",
//   "Haldur",
//   "Halstein",
//   "Halvar",
//   "Halvard",
//   "Halvur",
//   "Haskell",
//   "Herleif",
//   "Hjalmar",
//   "Hulkir",
//   "Ikur",
//   "Inkemir",
//   "Inkvar",
//   "Ivar",
//   "Iver",
//   "Jari",
//   "Jerrik",
//   "Keld",
//   "Kjeld",
//   "Knud",
//   "Kustaa",
//   "Lamont",
//   "Latham",
//   "Leif",
//   "Luf",
//   "Ulaf",
//   "Ulin",
//   "Uluf",
//   "Ranfvald",
//   "Sigurd",
//   "Stein",
//   "Stifr",
//   "Sven",
//   "Tarben",
//   "Turbjurn",
//   "Turvald",
//   "Ulf",
//   "Vidar",
//   "Vidar"];

//   female: ["Alfhild",
//   "Ase",
//   "Aslauk",
//   "Asluk",
//   "Asta",
//   "Astrid",
//   "Aubhild",
//   "Budil",
//   "Burfhild",
//   "Brenna",
//   "Dakmar",
//   "Dagny",
//   "Eira",
//   "Embla",
//   "Freja",
//   "Kerd",
//   "Kull",
//   "Kunhild",
//   "Kunvur",
//   "Gyda",
//   "Heke",
//   "Helka",
//   "Hertha",
//   "Inkebur",
//   "Inker",
//   "Inkrud",
//   "Jurunn",
//   "Kari",
//   "Maknhild",
//   "Ulka",
//   "Rakna",
//   "Saka",
//   "Sikfrid",
//   "Sikrid",
//   "Sikrun",
//   "Siv",
//   "Sulvik",
//   "Sulvi",
//   "Svurka",
//   "Thura",
//   "Turburk",
//   "Turhild",
//   "Tuve",
//   "Tyra",
//   "Ylva",
//   "Keld",
//   "Kjeld",
//   "Knud",
//   "Kustaa",
//   "Lamont",
//   "Latham",
//   "Leif",
//   "Luf",
//   "Ulaf",
//   "Ulin",
//   "Uluf",
//   "Ranfvald",
//   "Sigurd",
//   "Stein",
//   "Stifr",
//   "Sven",
//   "Tarben",
//   "Turbjurn",
//   "Turvald",
//   "Ulf",
//   "Vidar",
//   "Vidar"];
// };

function name_geerator () {
var elf_beginnings = ["Aces-",
  "Adri-",
  "Agas-",
  "Agno-",
  "Aith-",
  "All-",
  "Apol-",
  "Archi-",
  "Ari-",
  "Basil-",
  "Brasi-",
  "Cel-",
  "Cle-",
  "Damo-",
  "Dema-",
  "Dexi-",
  "Diag-",
  "Dio-",
  "Epi-",
  "Era-",
  "Euc-",
  "Eud-",
  "Gorg-",
  "Hag-",
  "Hec-",
  "Hera-",
  "Hero-",
  "Hesi-",
  "Hippi-",
  "Isa-",
  "Iso-",
  "Kar-",
  "Katak-",
  "Koi-",
  "Leo-",
  "Les-",
  "Lob-",
  "Ly-",
  "Marc-",
  "Meg-",
  "Mel-",
  "Met-",
  "Mil-",
  "Myr-",
  "Nic-",
  "Or-",
  "Ori-",
  "Pag-",
  "Pal-",
  "Pers-",
  "Phid-",
  "Prat-",
  "Prax-",
  "Proc-",
  "Pyr-",
  "Sat-",
  "Sel-",
  "Sim-",
  "Sos-",
  "Thalas-",
  "Thau-",
  "Thea-",
  "Theo-",
  "Thes-",
  "Xan-",
  "Xant-",
  "Xeno-", "Zal-", "Zen-"
  ];

var elf_endings_female = ["-a",
  "-lipha",
  "-na",
  "-theni",
  "-ili",
  "-anta",
  "-anti"];

var elf_endings_male = ["-us",
  "-liphon",
  "-nax",
  "-thenex",
  "-ilus",
  "-antus"];

randomNumber1 = parseInt (Math.random() * elf_beginnings.length);
randomNumber2 = parseInt (Math.random() * elf_endings_male.length);
randomNumber3 = parseInt (Math.random() * elf_endings_female.length);
var elf_name_male = elf_beginnings(randomNumber1) + ' ' + elf_endings_male(randomNumber2);
var elf_name_female = elf_beginnings(randomNumber1) + ' ' + elf_endings_female(randomNumber3);

alert (elf_name_male);
alert (elf_name_female)
}
